### PR TITLE
Change university name

### PR DESCRIPTION
**Pull request by ikura-hamu**
Tokyo Institute of Technology -> Institute of Science Tokyo

### CODE REVIEW

**Review by Takeno-hito — APPROVED** [review]
:+1:

**Comment by abap34** [comment]
If you are dissatisfied with this project, **fork it** and **develop it there.**

**Comment by ikura-hamu** [comment]
This university does not exist today. If you continue to use this name in your profile, your account may be regarded as an inactive one. I highly recommend you to update your profile.

**Comment by ikura-hamu** [comment]
I decided to respect your decision and I am going to develop this project in my repository.
I enabled the GitHub Pages in the forked repository, and deployed your profile page. 
https://ikura-hamu.github.io/abap34/

**Comment by EdamAme-x** [comment]
nice work

> I decided to respect your decision and I am going to develop this project in my repository. I enabled the GitHub Pages in the forked repository, and deployed your profile page. https://ikura-hamu.github.io/abap34/

**Pull request closed without merging**
